name: Setup kubeconform
description: A GitHub Action for running kubeconform commands
author: Stefan Prodan
branding:
  color: blue
  icon: command
inputs:
  version:
    description: "kubeconform version e.g. 0.5.0 (defaults to latest stable release)"
    required: false
  arch:
    description: "arch can be amd64 or arm64"
    required: true
    default: "amd64"
runs:
  using: composite
  steps:
    - name: "Download binary to the GH runner cache"
      shell: bash
      run: |  
        ARCH=${{ inputs.arch }}
        VERSION=${{ inputs.version }}

        if [ -z $VERSION ]; then
          VERSION=$(curl https://api.github.com/repos/yannh/kubeconform/releases/latest -sL | grep tag_name | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
        fi
        
        BIN_URL="https://github.com/yannh/kubeconform/releases/download/v${VERSION}/kubeconform-linux-${ARCH}.tar.gz"
        BIN_DIR=$RUNNER_TOOL_CACHE/kubeconform/$VERSION/$ARCH
        
        if [[ ! -x "$BIN_DIR/kind" ]]; then
          mkdir -p $BIN_DIR
          cd $BIN_DIR
          curl -sL $BIN_URL | tar xz
          chmod +x kubeconform
        fi
        
        echo "$BIN_DIR" >> "$GITHUB_PATH"
